# Generated by Django 4.2.2 on 2023-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='departamento',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='função',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='colaborador',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=''),
        ),
    ]
