# Generated by Django 4.2.2 on 2023-06-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0003_pesquisa_atitude_diante_mudanças_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesquisa',
            old_name='justificativa10',
            new_name='justificativa06',
        ),
    ]
