# Generated by Django 4.2.2 on 2023-06-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0004_rename_justificativa10_pesquisa_justificativa06'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='compromissos',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Selecione uma opção:'),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='pontos_fortes',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Selecione uma opção:'),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='pontos_reforçar',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Selecione uma opção:'),
        ),
    ]
