# Generated by Django 4.2.2 on 2023-06-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0007_alter_pesquisa_compromissos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='matrícula',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='atendimento_eficaz_cliente',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='atitude_diante_mudanças',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='atitude_positiva',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='compromissos',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='comunicação_com_liderança',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='criatividade_redução_custos',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='ideias_para_bom_ambiente',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='justificativa02',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='justificativa03',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='justificativa04',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='justificativa05',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='justificativa06',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='justificativa07',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='justificativa08',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='justificativa09',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='melhorar_qualidade',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='pontos_fortes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='pontos_reforçar',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='promoção_união',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='trabalho_em_equipe',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=''),
        ),
    ]
